# Generated by Django 5.0.6 on 2024-07-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('loan', 'Loan'), ('loan-paid', 'Loan paid')], max_length=20),
        ),
    ]
