# Generated by Django 5.0.6 on 2024-07-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('loan', 'Loan'), ('loan-paid', 'Loan paid'), ('balance-transfer', 'Balance transfer')], max_length=20),
        ),
    ]
